apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-csi
provisioner: ebs.csi.aws.com  # Ensure this is the correct CSI provisioner
parameters:
  type: gp2
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer
